### ISSUE TITLE
Photos in a grid

### ISSUE THREAD

**Issue by shelbyboyd** [shelbyboyd/portfolio#1]
@thomasjbradley 

I'm having trouble with my grid getting my photos to line up the way i want them to in the large screen. 
I like how in the small screen they are all stacked, medium screen the top image is large and the other two are side by side underneath the large one. For the large screen I want the first photo to take up 2/3 of the space, and the other two photos to sit beside it stacked, so the two smaller photos have the combined height of the first photo. like so:
[images for large screen.pdf](https://github.com/shelbyboyd/portfolio/files/7245/images.for.large.screen.pdf)

**Comment by thomasjbradley** [comment]
I think you'll need to have a `.grid` inside another `.grid`. I have a video that covers something very similar, check it out here: https://www.youtube.com/watch?list=PLWjCJDeWfDdeeD7gMjX8VTj-y6EFRMlkA&t=3&v=7hOycjGjjzQ
