### ISSUE TITLE
Spacing in Nav

### ISSUE THREAD

**Issue by valeriebordeleau** [shelbyboyd/portfolio#2]
![screen shot 2015-10-08 at 8 46 44 am](https://cloud.githubusercontent.com/assets/6373198/10366558/442a9d10-6d99-11e5-8c89-2110f5e138aa.png)

The spacing between items is a bit uneven. It's wider between portfolio and contact.

**Comment by valeriebordeleau** [comment]
![screen shot 2015-10-08 at 8 49 50 am](https://cloud.githubusercontent.com/assets/6373198/10366613/919bef2c-6d99-11e5-8488-a9ad3acee11f.png)

.svg image changes font on different browsers. I think it needs to be turned to outlines.

**Comment by benmarley** [comment]
windows 8 small nav breaks line; also back to top button extends slightly past the bottom of page
